### ISSUE TITLE
Problem Intensity-r1/rc estimation for spectral shape "lambda_f_lambda" 

### ISSUE THREAD

**Issue by jdrevon** [ivezic/dusty#6]
Hi,

 I think I've spotted a problem for the estimation of intensity when the user provide its own central source. The error have been spotted for the : spectral shape = file_lambda_f_lambda

Description of the problem : 

The problem of the intensity seems to come from the estimation of the r1/rc ratio. Since we are not in the case where the spectral shape is defined by an Engelke or Black Body profile, DUSTY does not have directly the value of the temperature provided by the user in order ot make an estimation of r1/rc using the formula provided in https://ui.adsabs.harvard.edu/abs/1997MNRAS.287..799I/abstract (Eq 14 and 27).

So first, I computed myself the r1rc ratio with the black body spectral shape option in order to check the value estimated by DUSTY using the two previous equations and my estimation matched with the one of DUSTY. But now if I provide manually the black body spectral shape using  file_lambda_f_lambda, I do not recover the same r1rc ratio but a ratio which seems to be very close to 2 instead of a ratio which is supposed to be equal to roughly ~4-5 as estimated with the BB spectral shape option just before.

The problem does not seem to come from the input file containing the spectral shape information because the output flux given by DUSTY is exactly the same and match completly between the two :  BB spectral shape and the file_lambda_f_lambda one.

So I don't know which is the method used to compute the r1rc ratio in the case where the spectral shape is file_lambda_f_lambda but the estimation seems to be incorrect.
Furthermore the estimated value is not "explicitly" displayed by DUSTY since in the ouput file in that case, r1rc is equal to 0 but should be at some point estimated by DUSTY since it provides us the intensity profile.

Cheers

Julien

**Comment by ivezic** [comment]
Please email from me (I need more info in order to debug this problem).

**Comment by ivezic** [comment]
I managed to reproduce your “problem”. I used quotation marks because it is 
a feature rather than a bug. When you provide a spectral shape, the source 
effective temperature is not known. The ratio r1/rc, and thus the width of the
central spike is not know either and a default temperature of 10^4 K is used
for the spike. This is explain in the last paragraph of section 5.2.2 in the manual
https://github.com/ivezic/dusty/blob/master/release/dusty/docs/manual.pdf

When you convolve the image, usually the spike is unresolved and what 
counts is the total flux, which doesn’t depend on Te (the integral is proportional
to height * width^2 \propto 1/Te^4 * Te^4.  If you really have a case of resolved
central source (I doubt it), then you could write a short program that would
rescale the width and height of the central spike to the actual Te. 

You may also want to take a look at this paper, which has related discussion:
http://faculty.washington.edu/ivezic/Publications/1996MNRAS.279.1011I.pdf

Please reopen this ticket if you need more information.
